services:
  app: #network
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 18
        PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - .env